menu:
    blog: /
    archive: /archives/
    rss: /atom.xml
    # about: /about/

favicon: /favicon.ico
logo: /favicon.ico

# Comment
# e.g disqus: seansun
disqus:
duoshuo:


# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2016
